version: '2.2'

services:

  front:
    image: ${DOCKER_ORG:-mailu}/nginx:${MAILU_VERSION:-master}
    restart: always
    env_file: .env
    logging:
      driver: $LOG_DRIVER
    ports:
#      - "$BIND_ADDRESS4:80:80"
#      - "$BIND_ADDRESS4:443:443"
      - "$BIND_ADDRESS4:110:110"
      - "$BIND_ADDRESS4:143:143"
      - "$BIND_ADDRESS4:993:993"
      - "$BIND_ADDRESS4:995:995"
      - "$BIND_ADDRESS4:25:25"
      - "$BIND_ADDRESS4:465:465"
      - "$BIND_ADDRESS4:587:587"
#      - "$BIND_ADDRESS6:80:80"
#      - "$BIND_ADDRESS6:443:443"
      - "$BIND_ADDRESS6:110:110"
      - "$BIND_ADDRESS6:143:143"
      - "$BIND_ADDRESS6:993:993"
      - "$BIND_ADDRESS6:995:995"
      - "$BIND_ADDRESS6:25:25"
      - "$BIND_ADDRESS6:465:465"
      - "$BIND_ADDRESS6:587:587"
    volumes:
      - "$ROOT/certs:/certs"
      - "$ROOT/overrides/nginx:/overrides:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:test.mailu.io"
      - "traefik.docker.network=web"
    networks:
      - web
      - default
      - webmail
    mem_limit: 150m
    cpus: 0.2
    depends_on:
      - resolver
    dns:
      - $DNS

  resolver:
    image: ${DOCKER_ORG:-mailu}/unbound:${MAILU_VERSION:-master}
    env_file: .env
    restart: always
    networks:
      default:
        ipv4_address: $DNS
      web:
    mem_limit: 150m
    cpus: 0.2

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "$ROOT/redis:/data"
    networks:
      - default
    depends_on:
      - resolver

  imap:
    image: ${DOCKER_ORG:-mailu}/dovecot:${MAILU_VERSION:-master}
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/mail:/mail"
      - "$ROOT/overrides:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - $DNS
    networks:
      - default
    blkio_config:
      weight: 100
    mem_limit: 250m
    cpus: 0.3

  smtp:
    image: ${DOCKER_ORG:-mailu}/postfix:${MAILU_VERSION:-master}
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/overrides:/overrides"
    depends_on:
      - front
      - resolver
    networks:
      - default
    dns:
      - $DNS
    blkio_config:
      weight: 100
    mem_limit: 250m
    cpus: 0.2

  oletools:
    image: ${DOCKER_ORG:-mailu}/oletools:${MAILU_VERSION:-master}
    hostname: oletools
    restart: always
    env_file: .env
    networks:
      - noinet
    mem_limit: 500m
    cpus: 0.5

  antispam:
    image: ${DOCKER_ORG:-mailu}/rspamd:${MAILU_VERSION:-master}
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/filter:/var/lib/rspamd"
      - "$ROOT/dkim:/dkim"
      - "$ROOT/overrides/rspamd:/etc/rspamd/override.d"
    depends_on:
      - front
      - redis
      - oletools
      - antivirus
      - resolver
    networks:
      - default
      - web
      - noinet
    dns:
      - $DNS
    mem_limit: 400m
    cpus: 0.2

  antivirus:
    image: ${DOCKER_ORG:-mailu}/$ANTIVIRUS:${MAILU_VERSION:-master}
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/filter:/data"
    networks:
      - default
      - web
    depends_on:
      - resolver
    dns:
      - $DNS
    blkio_config:
      weight: 100
    mem_limit: 2000m
    cpus: 0.75

  webdav:
    image: ${DOCKER_ORG:-mailu}/$WEBDAV:${MAILU_VERSION:-master}
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/dav:/data"
    networks:
      - radicale
    blkio_config:
      weight: 100
    mem_limit: 100m
    cpus: 0.1

  admin:
    image: ${DOCKER_ORG:-mailu}/admin:${MAILU_VERSION:-master}
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/data:/data"
      - "$ROOT/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - $DNS
    networks:
      - default
    mem_limit: 500m
    cpus: 0.5

  webmail:
    image: "${DOCKER_ORG:-mailu}/webmail:${MAILU_VERSION:-master}"
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/webmail:/data"
    networks:
      - webmail
    mem_limit: 500m
    cpus: 0.2

  fetchmail:
    image: ${DOCKER_ORG:-mailu}/fetchmail:${MAILU_VERSION:-master}
    restart: always
    env_file: .env
    networks:
      - default
      - web
    depends_on:
      - admin
      - smtp
      - imap
      - resolver
    dns:
      - $DNS
    mem_limit: 200m
    cpus: 0.2

  certdumper:
    restart: always
    image: ${DOCKER_ORG:-mailu}/traefik-certdumper:${MAILU_VERSION:-master}
    environment:
    # Make sure this is the same as the main=-domain in traefik.toml
    # !!! Also don’t forget to add "TRAEFIK_DOMAIN=[...]" to your .env!
      - DOMAIN=$TRAEFIK_DOMAIN
    volumes:
      - "/opt/traefik:/traefik"
      - "$ROOT/certs:/output"

networks:
  default:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: $SUBNET
  web:
    external: true
  radicale:
    driver: bridge
    internal: true
  webmail:
    driver: bridge
    internal: true
  noinet:
    driver: bridge
    internal: true
