# This file is used to run the mailu/setup utility

version: '3.6'

services:
  redis:
    image: redis:alpine
    networks:
      - default
    restart: always

  master:
    image: mailu/setup:master
    networks:
      - web
      - default
    env_file: .env
    environment:
      this_version: "master"
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.docker.network=web
      - traefik.main.frontend.rule=Host:${ADDRESS};PathPrefix:/master
    depends_on:
      - redis
    restart: always

  release:
    image: mailu/setup:${RELEASE}
    networks:
      - web
      - default
    env_file: .env
    environment:
      this_version: ${RELEASE}
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.docker.network=web
      - traefik.root.frontend.redirect.regex=.*
      - traefik.root.frontend.redirect.replacement=/${RELEASE}/
      - traefik.root.frontend.rule=Host:${ADDRESS};PathPrefix:/
      - traefik.main.frontend.rule=Host:${ADDRESS};PathPrefix:/${RELEASE}/
    depends_on:
      - redis
    restart: always

  beta:
    image: mailu/setup:1.7
    networks:
      - web
      - default
    env_file: .env
    environment:
      this_version: "1.7"
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.docker.network=web
      - traefik.main.frontend.rule=Host:${ADDRESS};PathPrefix:/1.7
    depends_on:
      - redis
    restart: always

networks:
  web:
    external: true
  default:
    external: false
