version: '3'

services:
  development:
    image: mailu/docs:${DEVELOPMENT}
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.main.frontend.rule=Host:${ADDRESS};PathPrefix:/${DEVELOPMENT}/
    restart: always

  stable:
    image: mailu/docs:${STABLE}
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.root.frontend.redirect.regex=.*
      - traefik.root.frontend.redirect.replacement=/${STABLE}/
      - traefik.root.frontend.rule=Host:${ADDRESS};PathPrefix:/
      - traefik.main.frontend.rule=Host:${ADDRESS};PathPrefix:/${STABLE}/
    restart: always

  oldstable:
    image: mailu/docs:${OLD_STABLE}
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.main.frontend.rule=Host:${ADDRESS};PathPrefix:/${OLD_STABLE}/
    restart: always

  legacy:
    image: mailu/docs:${LEGACY}
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.main.frontend.rule=Host:${ADDRESS};PathPrefix:/${LEGACY}/
    restart: always

networks:
  web:
    external: true
